// Code generated by goyacc asn1.y. DO NOT EDIT.

// asn1.y:3
package asn1go

import __yyfmt__ "fmt"

// asn1.y:3

import (
	"fmt"
	"math"
)

// asn1.y:15
type yySymType struct {
	yys        int
	name       string
	numberRepr string

	Number                            Number
	Real                              Real
	TagDefault                        int
	ExtensionDefault                  bool
	ModuleIdentifier                  ModuleIdentifier
	DefinitiveObjIdComponent          DefinitiveObjIdComponent
	DefinitiveObjIdComponentList      []DefinitiveObjIdComponent
	DefinitiveIdentifier              DefinitiveIdentifier
	Type                              Type
	ObjIdComponents                   ObjIdComponents
	DefinedValue                      DefinedValue
	ObjectIdentifierValue             ObjectIdentifierValue
	Value                             Value
	Assignment                        Assignment
	AssignmentList                    AssignmentList
	ModuleBody                        ModuleBody
	ValueReference                    ValueReference
	TypeReference                     TypeReference
	Constraint                        Constraint
	ConstraintSpec                    ConstraintSpec
	ElementSetSpec                    ElementSetSpec
	Unions                            Unions
	ModuleDefinition                  ModuleDefinition
	Intersections                     Intersections
	IntersectionElements              IntersectionElements
	Exclusions                        Exclusions
	Elements                          Elements
	SubtypeConstraint                 SubtypeConstraint
	RangeEndpoint                     RangeEndpoint
	NamedType                         NamedType
	ComponentType                     ComponentType
	ComponentTypeList                 ComponentTypeList
	IntegerEnumType                    IntegerEnumType
	IntegerEnumItemList                IntegerEnumItemList
	IntegerEnumItem                    IntegerEnumItem
	EnumeratedType                    EnumeratedType
	EnumeratedItemList                EnumeratedItemList
	EnumeratedItem                    EnumeratedItem
	SequenceType                      SequenceType
	SetType                           SetType
	Tag                               Tag
	Class                             int
	SequenceOfType                    SequenceOfType
	SetOfType                         SetOfType
	NamedBitList                      []NamedBit
	NamedBit                          NamedBit
	Imports                           []SymbolsFromModule
	SymbolsFromModule                 SymbolsFromModule
	SymbolList                        []Symbol
	Symbol                            Symbol
	GlobalModuleReference             GlobalModuleReference
	AlternativeTypeList               []NamedType
	ChoiceType                        ChoiceType
	ExtensionAdditionAlternative      ChoiceExtension
	ExtensionAdditionAlternativesList []ChoiceExtension
}

const WHITESPACE = 57346
const NEWLINE = 57347
const TYPEORMODULEREFERENCE = 57348
const VALUEIDENTIFIER = 57349
const NUMBER = 57350
const BSTRING = 57351
const XMLBSTRING = 57352
const HSTRING = 57353
const XMLHSTRING = 57354
const CSTRING = 57355
const XMLCSTRING = 57356
const ASSIGNMENT = 57357
const RANGE_SEPARATOR = 57358
const ELLIPSIS = 57359
const LEFT_VERSION_BRACKETS = 57360
const RIGHT_VERSION_BRACKETS = 57361
const XML_END_TAG_START = 57362
const XML_SINGLE_START_END = 57363
const XML_BOOLEAN_TRUE = 57364
const XML_BOOLEAN_FALSE = 57365
const XMLASN1TYPENAME = 57366
const EXPONENT = 57367
const OPEN_CURLY = 57368
const CLOSE_CURLY = 57369
const LESS = 57370
const GREATER = 57371
const COMMA = 57372
const DOT = 57373
const OPEN_ROUND = 57374
const CLOSE_ROUND = 57375
const OPEN_SQUARE = 57376
const CLOSE_SQUARE = 57377
const MINUS = 57378
const COLON = 57379
const EQUALS = 57380
const QUOTATION_MARK = 57381
const APOSTROPHE = 57382
const SPACE = 57383
const SEMICOLON = 57384
const AT = 57385
const PIPE = 57386
const EXCLAMATION = 57387
const CARET = 57388
const ABSENT = 57389
const ENCODED = 57390
const INTEGER = 57391
const RELATIVE_OID = 57392
const ABSTRACT_SYNTAX = 57393
const END = 57394
const INTERSECTION = 57395
const SEQUENCE = 57396
const ALL = 57397
const ENUMERATED = 57398
const ISO646String = 57399
const SET = 57400
const APPLICATION = 57401
const EXCEPT = 57402
const MAX = 57403
const SIZE = 57404
const AUTOMATIC = 57405
const EXPLICIT = 57406
const MIN = 57407
const STRING = 57408
const BEGIN = 57409
const EXPORTS = 57410
const MINUS_INFINITY = 57411
const SYNTAX = 57412
const BIT = 57413
const EXTENSIBILITY = 57414
const NULL = 57415
const T61String = 57416
const BMPString = 57417
const EXTERNAL = 57418
const NumericString = 57419
const TAGS = 57420
const BOOLEAN = 57421
const FALSE = 57422
const OBJECT = 57423
const TeletexString = 57424
const BY = 57425
const FROM = 57426
const ObjectDescriptor = 57427
const TRUE = 57428
const CHARACTER = 57429
const GeneralizedTime = 57430
const OCTET = 57431
const TYPE_IDENTIFIER = 57432
const CHOICE = 57433
const GeneralString = 57434
const OF = 57435
const UNION = 57436
const CLASS = 57437
const GraphicString = 57438
const OPTIONAL = 57439
const UNIQUE = 57440
const COMPONENT = 57441
const IA5String = 57442
const PATTERN = 57443
const UNIVERSAL = 57444
const COMPONENTS = 57445
const IDENTIFIER = 57446
const PDV = 57447
const UniversalString = 57448
const CONSTRAINED = 57449
const IMPLICIT = 57450
const PLUS_INFINITY = 57451
const UTCTime = 57452
const CONTAINING = 57453
const IMPLIED = 57454
const PRESENT = 57455
const UTF8String = 57456
const DEFAULT = 57457
const IMPORTS = 57458
const PrintableString = 57459
const VideotexString = 57460
const DEFINITIONS = 57461
const INCLUDES = 57462
const PRIVATE = 57463
const VisibleString = 57464
const EMBEDDED = 57465
const INSTANCE = 57466
const REAL = 57467
const WITH = 57468

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"WHITESPACE",
	"NEWLINE",
	"TYPEORMODULEREFERENCE",
	"VALUEIDENTIFIER",
	"NUMBER",
	"BSTRING",
	"XMLBSTRING",
	"HSTRING",
	"XMLHSTRING",
	"CSTRING",
	"XMLCSTRING",
	"ASSIGNMENT",
	"RANGE_SEPARATOR",
	"ELLIPSIS",
	"LEFT_VERSION_BRACKETS",
	"RIGHT_VERSION_BRACKETS",
	"XML_END_TAG_START",
	"XML_SINGLE_START_END",
	"XML_BOOLEAN_TRUE",
	"XML_BOOLEAN_FALSE",
	"XMLASN1TYPENAME",
	"EXPONENT",
	"OPEN_CURLY",
	"CLOSE_CURLY",
	"LESS",
	"GREATER",
	"COMMA",
	"DOT",
	"OPEN_ROUND",
	"CLOSE_ROUND",
	"OPEN_SQUARE",
	"CLOSE_SQUARE",
	"MINUS",
	"COLON",
	"EQUALS",
	"QUOTATION_MARK",
	"APOSTROPHE",
	"SPACE",
	"SEMICOLON",
	"AT",
	"PIPE",
	"EXCLAMATION",
	"CARET",
	"ABSENT",
	"ENCODED",
	"INTEGER",
	"RELATIVE_OID",
	"ABSTRACT_SYNTAX",
	"END",
	"INTERSECTION",
	"SEQUENCE",
	"ALL",
	"ENUMERATED",
	"ISO646String",
	"SET",
	"APPLICATION",
	"EXCEPT",
	"MAX",
	"SIZE",
	"AUTOMATIC",
	"EXPLICIT",
	"MIN",
	"STRING",
	"BEGIN",
	"EXPORTS",
	"MINUS_INFINITY",
	"SYNTAX",
	"BIT",
	"EXTENSIBILITY",
	"NULL",
	"T61String",
	"BMPString",
	"EXTERNAL",
	"NumericString",
	"TAGS",
	"BOOLEAN",
	"FALSE",
	"OBJECT",
	"TeletexString",
	"BY",
	"FROM",
	"ObjectDescriptor",
	"TRUE",
	"CHARACTER",
	"GeneralizedTime",
	"OCTET",
	"TYPE_IDENTIFIER",
	"CHOICE",
	"GeneralString",
	"OF",
	"UNION",
	"CLASS",
	"GraphicString",
	"OPTIONAL",
	"UNIQUE",
	"COMPONENT",
	"IA5String",
	"PATTERN",
	"UNIVERSAL",
	"COMPONENTS",
	"IDENTIFIER",
	"PDV",
	"UniversalString",
	"CONSTRAINED",
	"IMPLICIT",
	"PLUS_INFINITY",
	"UTCTime",
	"CONTAINING",
	"IMPLIED",
	"PRESENT",
	"UTF8String",
	"DEFAULT",
	"IMPORTS",
	"PrintableString",
	"VideotexString",
	"DEFINITIONS",
	"INCLUDES",
	"PRIVATE",
	"VisibleString",
	"EMBEDDED",
	"INSTANCE",
	"REAL",
	"WITH",
	"\"t\"",
	"\"o\"",
	"\"d\"",
	"\",\"",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

// asn1.y:1030

// yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 33,
	52, 26,
	-2, 29,
	-1, 176,
	44, 233,
	94, 233,
	-2, 229,
	-1, 178,
	46, 236,
	53, 236,
	-2, 231,
	-1, 182,
	60, 239,
	-2, 237,
	-1, 190,
	16, 257,
	28, 257,
	-2, 251,
	-1, 322,
	46, 236,
	53, 236,
	-2, 232,
}

const yyPrivate = 57344

const yyLast = 791

var yyAct = [...]int16{
	162, 382, 285, 306, 161, 175, 310, 217, 272, 341,
	19, 326, 248, 216, 208, 192, 19, 203, 190, 204,
	178, 211, 180, 244, 168, 256, 259, 158, 182, 157,
	212, 351, 127, 372, 318, 57, 21, 330, 300, 342,
	7, 21, 251, 290, 234, 148, 251, 163, 40, 47,
	4, 4, 31, 13, 11, 133, 140, 292, 222, 135,
	221, 291, 319, 120, 262, 128, 188, 319, 37, 26,
	21, 25, 67, 64, 24, 23, 33, 145, 95, 21,
	213, 134, 125, 101, 21, 96, 110, 102, 147, 213,
	224, 129, 260, 38, 265, 139, 257, 121, 12, 210,
	90, 266, 97, 114, 106, 303, 111, 149, 91, 44,
	98, 113, 63, 62, 263, 302, 119, 105, 99, 142,
	94, 107, 301, 141, 60, 108, 136, 123, 299, 109,
	379, 199, 205, 209, 137, 115, 199, 199, 198, 378,
	331, 199, 199, 116, 220, 152, 112, 117, 235, 228,
	233, 118, 219, 235, 100, 238, 232, 227, 235, 229,
	230, 235, 225, 235, 250, 235, 218, 245, 138, 21,
	166, 226, 223, 151, 124, 218, 61, 239, 240, 243,
	218, 237, 241, 52, 122, 49, 50, 373, 163, 128,
	311, 268, 255, 48, 357, 126, 273, 371, 167, 370,
	369, 154, 368, 104, 384, 324, 313, 242, 34, 128,
	267, 270, 128, 367, 43, 276, 366, 332, 312, 253,
	308, 284, 199, 199, 281, 252, 286, 29, 297, 294,
	296, 170, 365, 56, 42, 65, 359, 293, 295, 288,
	170, 46, 160, 55, 46, 56, 250, 250, 159, 282,
	279, 277, 283, 280, 278, 55, 289, 275, 258, 64,
	352, 316, 315, 46, 350, 17, 345, 255, 46, 305,
	307, 169, 21, 317, 304, 298, 199, 287, 274, 336,
	169, 338, 322, 334, 209, 340, 339, 323, 328, 321,
	199, 21, 206, 27, 344, 32, 335, 333, 343, 195,
	337, 132, 131, 347, 130, 9, 355, 21, 349, 346,
	348, 201, 354, 320, 247, 269, 66, 213, 14, 30,
	234, 353, 21, 20, 16, 358, 356, 309, 243, 254,
	16, 20, 273, 21, 28, 5, 363, 49, 50, 360,
	361, 314, 362, 57, 50, 2, 328, 6, 264, 261,
	200, 41, 36, 1, 57, 21, 166, 381, 364, 197,
	196, 74, 374, 150, 236, 377, 199, 380, 45, 59,
	340, 339, 58, 383, 163, 39, 375, 271, 71, 80,
	185, 88, 120, 146, 167, 199, 385, 154, 231, 103,
	86, 214, 383, 215, 85, 83, 84, 95, 82, 202,
	75, 207, 101, 177, 96, 110, 102, 76, 69, 87,
	139, 93, 92, 194, 73, 193, 325, 170, 191, 90,
	189, 97, 114, 106, 184, 111, 187, 91, 160, 98,
	113, 186, 183, 181, 159, 119, 105, 99, 179, 94,
	107, 57, 21, 166, 108, 176, 376, 174, 109, 173,
	172, 171, 89, 70, 115, 35, 51, 169, 53, 54,
	165, 163, 116, 164, 155, 112, 117, 185, 81, 120,
	118, 167, 156, 100, 154, 153, 249, 246, 78, 68,
	72, 77, 79, 8, 95, 18, 15, 3, 10, 101,
	22, 96, 110, 102, 0, 0, 0, 139, 0, 0,
	194, 0, 0, 0, 170, 0, 90, 0, 97, 114,
	106, 0, 111, 0, 91, 160, 98, 113, 57, 0,
	318, 159, 119, 105, 99, 0, 94, 107, 0, 0,
	0, 108, 0, 0, 0, 109, 0, 0, 0, 0,
	0, 115, 0, 0, 169, 0, 120, 0, 319, 116,
	0, 0, 112, 117, 0, 0, 0, 118, 0, 0,
	100, 95, 0, 0, 0, 0, 101, 0, 96, 110,
	102, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 90, 0, 97, 114, 106, 0, 111,
	0, 91, 57, 98, 113, 0, 0, 0, 0, 119,
	105, 99, 0, 94, 107, 0, 0, 0, 108, 0,
	0, 0, 109, 0, 0, 0, 0, 0, 115, 0,
	120, 0, 21, 166, 0, 0, 116, 0, 0, 112,
	117, 0, 0, 0, 118, 95, 0, 100, 0, 235,
	101, 163, 96, 110, 102, 0, 0, 0, 0, 0,
	144, 167, 0, 0, 154, 0, 0, 90, 0, 97,
	114, 106, 57, 111, 0, 91, 0, 98, 113, 0,
	0, 0, 0, 119, 105, 99, 329, 94, 107, 0,
	0, 0, 108, 0, 170, 0, 109, 0, 21, 166,
	120, 0, 115, 0, 143, 160, 0, 0, 0, 0,
	116, 159, 0, 112, 117, 95, 0, 163, 118, 327,
	101, 100, 96, 110, 102, 0, 0, 167, 0, 0,
	154, 0, 0, 0, 169, 0, 0, 90, 0, 97,
	114, 106, 0, 111, 0, 91, 0, 98, 113, 0,
	0, 0, 329, 119, 105, 99, 0, 94, 107, 0,
	170, 0, 108, 0, 0, 0, 109, 0, 0, 0,
	0, 160, 115, 0, 0, 0, 0, 159, 0, 0,
	116, 0, 0, 112, 117, 0, 0, 0, 118, 0,
	0, 100, 0, 0, 0, 0, 0, 0, 0, 0,
	169,
}

var yyPact = [...]int16{
	329, 329, -1000, -79, 279, -1000, -1000, -10, -1000, 315,
	3, -4, -7, -9, 266, 315, -1000, -1000, -1000, 195,
	-1000, -1000, 304, -60, -1000, -1000, -1000, -1000, -1000, 323,
	9, -1000, 175, 0, -1000, 41, -68, 179, -1000, 337,
	331, 71, 70, 229, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 337, -1000, -1000, -1000, 301, 656, -1000, 55, 331,
	-1000, 43, -1000, -1000, 331, -1000, 656, 180, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	25, -1000, -1000, -1000, 278, 276, 275, -1000, -49, 15,
	-1000, 33, 30, 586, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 11,
	-14, -1000, -1000, 329, -1000, 177, 162, -1000, 348, 273,
	326, 284, 265, -1000, -1000, 72, 29, -33, -35, 177,
	63, 29, 177, 656, 656, -1000, 36, -1000, -1000, -1000,
	-1000, 21, -1000, -1000, 171, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 34, -1000, -1000, 194, 321, -1000, -1000,
	-1000, 51, -1000, -1000, 228, -1000, -1000, 32, -1000, 20,
	-1000, 48, -1000, 32, -1000, 348, -1000, -1000, -1000, -1000,
	-1000, 299, 177, 183, -1000, 326, 251, 227, -1000, 656,
	224, -1000, 223, -1000, -1000, 192, -1000, 222, -1000, 189,
	-1000, 196, 250, 51, -1000, 226, -1000, -54, -36, 177,
	-1000, 29, 29, -1000, -1000, 196, 248, 177, -1000, 177,
	177, 93, -1000, -1000, -1000, -90, -1000, -1000, -1000, 83,
	76, 66, 320, 194, 247, 34, 34, -1000, -1000, -1000,
	188, -1000, 319, 182, 194, -1000, 173, 512, 296, -1000,
	435, 435, -1000, -1000, 435, -1000, -1000, -1000, 172, 681,
	-1000, 10, -1000, 185, -1000, 300, 177, -1000, 326, -1000,
	326, 31, -1000, 326, 312, 239, 292, -1000, -1000, 77,
	-1000, 162, 656, 177, -1000, 177, -1000, 237, -1000, -1000,
	-98, -1000, -1000, -1000, -1000, 233, -1000, -1000, 38, 281,
	-1000, -1000, 318, -1000, -1000, -1000, -1000, 157, -1000, 317,
	206, -1000, -1000, -1000, -1000, -1000, -1000, 615, -1000, -1000,
	-1000, 326, 36, 202, -1000, -1000, 184, -1000, 181, 169,
	167, 166, -1000, -1000, 164, -1000, -1000, -1000, -1000, 177,
	-1000, -95, -1000, 154, -1000, 182, -1000, 162, -1000, 348,
	-1000, -1000, 106, 97, 196, 326, 26, 312, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 174, -1000, -1000, 326, -1000,
}

var yyPgo = [...]int16{
	0, 24, 6, 49, 203, 0, 490, 488, 487, 486,
	265, 318, 485, 483, 314, 3, 482, 481, 480, 479,
	15, 478, 7, 477, 12, 476, 23, 29, 475, 18,
	472, 468, 27, 464, 463, 460, 4, 9, 183, 459,
	458, 456, 455, 193, 453, 452, 32, 451, 450, 449,
	447, 446, 5, 445, 438, 20, 433, 22, 26, 28,
	432, 431, 426, 424, 420, 66, 418, 416, 415, 11,
	414, 412, 411, 409, 408, 407, 401, 14, 400, 399,
	19, 398, 396, 395, 394, 13, 393, 391, 30, 390,
	389, 388, 383, 381, 379, 378, 377, 8, 375, 372,
	369, 124, 176, 109, 368, 364, 363, 361, 360, 359,
	359, 1, 358, 357, 345, 353, 352, 351, 350, 17,
	21, 2, 25, 350, 350, 350, 350, 350, 350, 350,
	349, 348, 341,
}

var yyR1 = [...]uint8{
	0, 115, 115, 114, 4, 3, 43, 37, 5, 8,
	13, 13, 11, 11, 9, 9, 9, 10, 12, 7,
	7, 7, 7, 6, 6, 42, 42, 116, 116, 116,
	117, 117, 98, 98, 99, 99, 100, 100, 101, 106,
	105, 105, 105, 102, 102, 103, 104, 104, 104, 41,
	41, 38, 38, 73, 15, 40, 39, 20, 20, 20,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 74, 74, 22, 29,
	29, 29, 29, 28, 28, 28, 28, 18, 33, 33,
	17, 17, 118, 118, 119, 119, 36, 36, 30, 30,
	31, 32, 32, 34, 34, 35, 35, 1, 1, 1,
	1, 2, 2, 95, 95, 96, 96, 97, 97, 94,
	21, 78, 78, 79, 79, 80, 75, 75, 76, 76,
	77, 82, 82, 82, 81, 81, 81, 120, 120, 121,
	121, 88, 87, 123, 124, 124, 125, 125, 126, 126,
	127, 128, 128, 86, 86, 85, 85, 85, 85, 107,
	108, 108, 110, 112, 112, 113, 113, 111, 129, 109,
	109, 89, 89, 89, 90, 91, 91, 92, 92, 92,
	92, 83, 83, 84, 84, 16, 27, 27, 26, 26,
	23, 23, 23, 23, 24, 24, 25, 14, 70, 70,
	71, 71, 71, 71, 71, 71, 71, 71, 71, 71,
	71, 71, 71, 72, 93, 44, 44, 45, 45, 45,
	45, 46, 47, 48, 49, 49, 49, 50, 51, 52,
	52, 53, 53, 54, 55, 55, 56, 57, 57, 60,
	58, 130, 130, 131, 131, 59, 59, 63, 63, 63,
	63, 61, 62, 66, 66, 67, 67, 68, 68, 69,
	69, 65, 64, 122, 122, 132, 132, 132,
}

var yyR2 = [...]int8{
	0, 1, 2, 8, 1, 1, 1, 1, 1, 2,
	3, 0, 1, 2, 1, 1, 1, 1, 4, 2,
	2, 2, 0, 2, 0, 3, 0, 3, 3, 0,
	1, 0, 3, 0, 1, 0, 1, 2, 3, 2,
	1, 1, 0, 1, 3, 1, 1, 1, 1, 1,
	2, 1, 1, 1, 4, 3, 4, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
	3, 3, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 4, 1, 3, 4, 4, 1, 2, 1, 1,
	1, 1, 1, 1, 2, 1, 1, 1, 3, 5,
	3, 1, 2, 2, 5, 1, 3, 4, 4, 2,
	1, 3, 4, 1, 3, 4, 3, 4, 1, 3,
	4, 3, 5, 4, 3, 5, 4, 1, 2, 2,
	0, 1, 1, 2, 2, 0, 1, 3, 1, 1,
	4, 0, 2, 1, 3, 1, 2, 3, 3, 4,
	5, 1, 1, 2, 0, 1, 3, 1, 4, 1,
	3, 2, 3, 3, 4, 1, 1, 1, 1, 1,
	0, 3, 3, 3, 3, 2, 3, 4, 1, 2,
	1, 1, 1, 1, 1, 1, 4, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 2, 1, 2, 1, 4, 4, 4,
	4, 4, 1, 1, 1, 3, 5, 1, 1, 1,
	2, 1, 3, 1, 1, 3, 1, 1, 2, 1,
	2, 1, 1, 1, 1, 1, 3, 1, 1, 1,
	1, 1, 3, 1, 2, 1, 2, 1, 1, 1,
	1, 2, 1, 2, 0, 1, 1, 3,
}

var yyChk = [...]int16{
	-1000, -115, -114, -8, -3, 6, -114, 119, -13, 26,
	-7, 64, 108, 63, -11, -9, -14, -10, -12, -5,
	8, 7, -6, 72, 78, 78, 78, 27, -11, 32,
	15, 112, -10, 67, 33, -42, -116, 68, 52, -98,
	116, -117, 55, -102, -103, -104, -4, -3, -43, 6,
	7, -41, -38, -40, -39, -4, -43, 6, -99, -100,
	-101, -102, 42, 42, 30, -38, 15, -20, -19, -74,
	-44, -95, -18, -70, -107, -78, -75, -17, -21, -16,
	-94, -31, -81, -83, -82, -84, -89, -73, -93, -45,
	71, 79, -71, -72, 91, 49, 56, 73, 81, 89,
	125, 54, 58, -90, -4, 88, 75, 92, 96, 100,
	57, 77, 117, 82, 74, 106, 114, 118, 122, 87,
	34, 42, -101, 84, -103, -20, 15, -46, 32, 66,
	26, 26, 26, 104, 66, 26, 93, -46, -65, 62,
	26, 93, -20, 108, 64, 66, -92, 102, 59, 121,
	-106, -3, -29, -28, 39, -33, -30, -27, -32, 86,
	80, -36, -5, 26, -34, -35, 8, 36, -1, 109,
	69, -47, -48, -49, -50, -52, -53, 55, -55, -54,
	-57, -56, -59, -60, -63, 32, -61, -62, -65, -64,
	-29, -66, -20, -68, 65, 26, -108, -109, -22, -5,
	-118, 27, -79, -119, -80, -5, 27, -76, -77, -5,
	27, -120, -88, 17, -87, -86, -85, -22, 103, -20,
	-22, 93, 93, -46, 27, -120, -88, -20, -22, -20,
	-20, -91, -37, -15, 8, 127, -105, -27, -15, 6,
	7, -32, 36, 8, -26, -15, -23, -14, -24, -25,
	-5, 8, 31, 25, 8, -1, -122, 45, 30, -58,
	60, -130, 44, 94, -131, 46, 53, -58, -52, 16,
	28, -96, -97, -5, 27, 30, -20, 27, 30, 27,
	30, 32, 27, 30, 32, -121, 30, 27, -122, 30,
	97, 115, 93, -20, -22, -20, -22, -121, 27, 35,
	128, 39, 39, 39, 27, -26, -15, -26, 32, 8,
	-2, 8, 36, 33, -132, -36, -15, -20, 8, 36,
	17, -59, -55, -57, 33, -67, -69, 28, -29, 61,
	27, 130, 32, -120, -22, -119, -5, -80, -5, -36,
	-15, -37, 8, -77, -37, 27, 17, -85, -29, -20,
	27, 129, 27, -24, -15, 25, 8, 37, 8, 30,
	-69, -97, -37, -15, -112, 30, 32, 32, 33, 33,
	33, 33, 128, 33, -2, -29, -51, -52, 33, 33,
	-121, -113, -111, -22, 30, -111,
}

var yyDef = [...]int16{
	0, -2, 1, 0, 11, 5, 2, 22, 9, 0,
	24, 0, 0, 0, 0, 12, 14, 15, 16, 197,
	17, 8, 0, 0, 19, 20, 21, 10, 13, 0,
	0, 23, 0, -2, 18, 0, 33, 31, 3, 0,
	35, 0, 0, 30, 43, 45, 46, 47, 48, 4,
	6, 25, 49, 51, 52, 0, 0, 4, 0, 34,
	36, 0, 27, 28, 0, 50, 0, 0, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
	69, 70, 71, 72, 73, 74, 75, 76, 77, 216,
	0, 87, 198, 199, 0, 90, 0, 120, 0, 0,
	100, 0, 0, 0, 53, 214, 200, 201, 202, 203,
	204, 205, 206, 207, 208, 209, 210, 211, 212, 0,
	180, 32, 37, 0, 44, 55, 0, 215, 0, 113,
	0, 0, 0, 185, 119, 0, 0, 0, 0, 0,
	0, 0, 171, 0, 0, 213, 0, 177, 178, 179,
	38, 42, 56, 79, 0, 83, 84, 85, 86, 88,
	89, 98, 99, 0, 101, 102, 96, 0, 103, 105,
	106, 264, 222, 223, 224, 227, -2, 0, -2, 0,
	234, 0, -2, 0, 245, 0, 247, 248, 249, 250,
	-2, 0, 262, 253, 258, 0, 0, 161, 169, 0,
	0, 121, 0, 92, 123, 0, 126, 0, 128, 0,
	134, 140, 0, 137, 141, 142, 153, 155, 0, 181,
	182, 0, 0, 261, 131, 140, 0, 183, 184, 172,
	173, 0, 175, 176, 7, 0, 39, 40, 41, 0,
	0, 0, 0, 107, 0, 193, 188, 190, 191, 192,
	197, 194, 0, 0, 97, 104, 0, 0, 0, 230,
	0, 0, 241, 242, 0, 243, 244, 238, 0, 0,
	254, 0, 115, 0, 159, 0, 78, 91, 0, 122,
	0, 0, 127, 0, 0, 0, 0, 136, 138, 0,
	156, 0, 0, 217, 219, 218, 220, 0, 133, 174,
	0, 80, 81, 82, 186, 0, 193, 189, 0, 108,
	110, 111, 0, 221, 263, 265, 266, 0, 96, 0,
	225, 240, -2, 235, 246, 252, 255, 0, 259, 260,
	114, 0, 0, 164, 170, 93, 0, 124, 0, 0,
	0, 0, 7, 129, 0, 135, 139, 154, 157, 158,
	132, 0, 187, 0, 195, 0, 112, 0, 97, 0,
	256, 116, 0, 0, 140, 0, 0, 0, 94, 95,
	125, 130, 54, 196, 109, 267, 226, 228, 117, 118,
	160, 163, 165, 167, 0, 166,
}

var yyTok1 = [...]uint8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 130, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	129, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 128, 3, 3, 3, 3, 127,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

// yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:329
		{
			yylex.(*MyLexer).result = append(make([]ModuleDefinition, 0), yyDollar[1].ModuleDefinition)
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:330
		{
			yylex.(*MyLexer).result = append(yylex.(*MyLexer).result, yyDollar[2].ModuleDefinition)
		}
	case 3:
		yyDollar = yyS[yypt-8 : yypt+1]
// asn1.y:343
		{
			yyVAL.ModuleDefinition = ModuleDefinition{ModuleIdentifier: yyDollar[1].ModuleIdentifier, TagDefault: yyDollar[3].TagDefault, ExtensibilityImplied: yyDollar[4].ExtensionDefault, ModuleBody: yyDollar[7].ModuleBody}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:348
		{
			yyVAL.TypeReference = TypeReference(yyDollar[1].name)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:353
		{
			yyVAL.ValueReference = ValueReference(yyDollar[1].name)
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:364
		{
			yyVAL.ModuleIdentifier = ModuleIdentifier{Reference: yyDollar[1].name, DefinitiveIdentifier: yyDollar[2].DefinitiveIdentifier}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:367
		{
			yyVAL.DefinitiveIdentifier = DefinitiveIdentifier(yyDollar[2].DefinitiveObjIdComponentList)
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:368
		{
			yyVAL.DefinitiveIdentifier = DefinitiveIdentifier(make([]DefinitiveObjIdComponent, 0))
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:371
		{
			yyVAL.DefinitiveObjIdComponentList = append(make([]DefinitiveObjIdComponent, 0), yyDollar[1].DefinitiveObjIdComponent)
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:372
		{
			yyVAL.DefinitiveObjIdComponentList = append(append(make([]DefinitiveObjIdComponent, 0), yyDollar[1].DefinitiveObjIdComponent), yyDollar[2].DefinitiveObjIdComponentList...)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:375
		{
			yyVAL.DefinitiveObjIdComponent = DefinitiveObjIdComponent{Name: yyDollar[1].name}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:376
		{
			yyVAL.DefinitiveObjIdComponent = DefinitiveObjIdComponent{Id: yyDollar[1].Number.IntValue()}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:377
		{
			yyVAL.DefinitiveObjIdComponent = yyDollar[1].DefinitiveObjIdComponent
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:380
		{
			yyVAL.Number = yyDollar[1].Number
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:384
		{
			yyVAL.DefinitiveObjIdComponent = DefinitiveObjIdComponent{Name: yyDollar[1].name, Id: yyDollar[3].Number.IntValue()}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:387
		{
			yyVAL.TagDefault = TAGS_EXPLICIT
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:388
		{
			yyVAL.TagDefault = TAGS_IMPLICIT
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:389
		{
			yyVAL.TagDefault = TAGS_AUTOMATIC
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:390
		{
			yyVAL.TagDefault = TAGS_EXPLICIT
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:393
		{
			yyVAL.ExtensionDefault = true
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:394
		{
			yyVAL.ExtensionDefault = false
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:397
		{
			yyVAL.ModuleBody = ModuleBody{Imports: yyDollar[2].Imports, AssignmentList: yyDollar[3].AssignmentList}
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:398
		{
			yyVAL.ModuleBody = ModuleBody{}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:411
		{
			yyVAL.Imports = yyDollar[2].Imports
		}
	case 33:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:412
		{
			yyVAL.Imports = make([]SymbolsFromModule, 0)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:415
		{
			yyVAL.Imports = yyDollar[1].Imports
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:416
		{
			yyVAL.Imports = make([]SymbolsFromModule, 0)
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:419
		{
			yyVAL.Imports = append(make([]SymbolsFromModule, 0), yyDollar[1].SymbolsFromModule)
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:420
		{
			yyVAL.Imports = append(yyDollar[1].Imports, yyDollar[2].SymbolsFromModule)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:423
		{
			yyVAL.SymbolsFromModule = SymbolsFromModule{yyDollar[1].SymbolList, yyDollar[3].GlobalModuleReference}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:426
		{
			yyVAL.GlobalModuleReference = GlobalModuleReference{yyDollar[1].name, yyDollar[2].Value}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:429
		{
			yyVAL.Value = yyDollar[1].ObjectIdentifierValue
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:430
		{
			yyVAL.Value = yyDollar[1].DefinedValue
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:431
		{
			yyVAL.Value = nil
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:434
		{
			yyVAL.SymbolList = append(make([]Symbol, 0), yyDollar[1].Symbol)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:435
		{
			yyVAL.SymbolList = append(yyDollar[1].SymbolList, yyDollar[3].Symbol)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:442
		{
			yyVAL.Symbol = TypeReference(yyDollar[1].TypeReference)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:443
		{
			yyVAL.Symbol = ModuleReference(yyDollar[1].name)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:444
		{
			yyVAL.Symbol = ValueReference(yyDollar[1].ValueReference)
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:450
		{
			yyVAL.AssignmentList = NewAssignmentList(yyDollar[1].Assignment)
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:451
		{
			yyVAL.AssignmentList = yyDollar[1].AssignmentList.Append(yyDollar[2].Assignment)
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:467
		{
			yyVAL.Type = yyDollar[1].TypeReference
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:474
		{
			yyVAL.DefinedValue = DefinedValue{}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:482
		{
			yyVAL.Assignment = TypeAssignment{yyDollar[1].TypeReference, yyDollar[3].Type, ""}
		}
	case 56:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:485
		{
			yyVAL.Assignment = ValueAssignment{yyDollar[1].ValueReference, yyDollar[2].Type, yyDollar[4].Value}
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:531
		{
			yyVAL.NamedType = NamedType{Identifier: Identifier(yyDollar[1].name), Type: yyDollar[2].Type}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:539
		{
			yyVAL.Value = String(yyDollar[2].name)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:540
		{
			yyVAL.Value = String(yyDollar[2].name)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:541
		{
			yyVAL.Value = yyDollar[2].Value
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:557
		{
			yyVAL.Value = yyDollar[1].ObjectIdentifierValue
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:570
		{
			yyVAL.Type = BooleanType{}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:573
		{
			yyVAL.Value = Boolean(true)
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:574
		{
			yyVAL.Value = Boolean(false)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:579
		{
			yyVAL.Type = IntegerType{}
		}
	case 91:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:580
		{
			yyVAL.Type = IntegerType{}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:591
		{
			yyVAL.Number = yyDollar[1].Number
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:592
		{
			yyVAL.Number = yyDollar[2].Number.UnaryMinus()
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:597
		{
			yyVAL.Value = yyDollar[1].Number
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:598
		{
			yyVAL.Value = IdentifiedIntegerValue{Name: yyDollar[1].name}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:603
		{
			yyVAL.Type = RealType{}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:612
		{
			yyVAL.Value = yyDollar[1].Real
		}
	case 104:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:613
		{
			yyVAL.Value = yyDollar[2].Real.UnaryMinus()
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:617
		{
			yyVAL.Value = Real(math.Inf(1))
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:618
		{
			yyVAL.Value = Real(math.Inf(-1))
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:622
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, 0, 0)
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:623
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, yyDollar[3].Number, 0)
		}
	case 109:
		yyDollar = yyS[yypt-5 : yypt+1]
// asn1.y:624
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, yyDollar[3].Number, yyDollar[5].Number)
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:625
		{
			yyVAL.Real = parseRealNumber(yyDollar[1].Number, 0, yyDollar[3].Number)
		}
	case 112:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:629
		{
			yyVAL.Number = Number(-int(yyDollar[2].Number))
		}
	case 113:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:634
		{
			yyVAL.Type = BitStringType{}
		}
	case 114:
		yyDollar = yyS[yypt-5 : yypt+1]
// asn1.y:635
		{
			yyVAL.Type = BitStringType{NamedBits: yyDollar[4].NamedBitList}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:638
		{
			yyVAL.NamedBitList = append(make([]NamedBit, 0), yyDollar[1].NamedBit)
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:639
		{
			yyVAL.NamedBitList = append(yyDollar[1].NamedBitList, yyDollar[3].NamedBit)
		}
	case 117:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:642
		{
			yyVAL.NamedBit = NamedBit{Name: Identifier(yyDollar[1].name), Index: yyDollar[3].Number}
		}
	case 118:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:643
		{
			yyVAL.NamedBit = NamedBit{Name: Identifier(yyDollar[1].name), Index: yyDollar[3].DefinedValue}
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:648
		{
			yyVAL.Type = OctetStringType{}
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:653
		{
			yyVAL.Type = NullType{}
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:656
		{
			yyVAL.Type = IntegerEnumType{}
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:657
		{
			yyVAL.Type = IntegerEnumType{Enums: yyDollar[3].IntegerEnumItemList}
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:659
		{
			yyVAL.IntegerEnumItemList = append(make(IntegerEnumItemList, 0), yyDollar[1].IntegerEnumItem)
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:660
		{
			yyVAL.IntegerEnumItemList = append(yyDollar[1].IntegerEnumItemList, yyDollar[3].IntegerEnumItem)
		}
	case 125:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:663
		{
			yyVAL.IntegerEnumItem = IntegerEnumItem{Name: Identifier(yyDollar[1].name), Index: yyDollar[3].Number}
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:668
		{
			yyVAL.Type = EnumeratedType{}
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:669
		{
			yyVAL.Type = EnumeratedType{Enums: yyDollar[3].EnumeratedItemList}
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:671
		{
			yyVAL.EnumeratedItemList = append(make(EnumeratedItemList, 0), yyDollar[1].EnumeratedItem)
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:672
		{
			yyVAL.EnumeratedItemList = append(yyDollar[1].EnumeratedItemList, yyDollar[3].EnumeratedItem)
		}
	case 130:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:675
		{
			yyVAL.EnumeratedItem = EnumeratedItem{Name: Identifier(yyDollar[1].name), Index: yyDollar[3].Number}
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:679
		{
			yyVAL.Type = SetType{}
		}
	case 132:
		yyDollar = yyS[yypt-5 : yypt+1]
// asn1.y:680
		{
			yyVAL.Type = SetType{}
		}
	case 133:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:681
		{
			yyVAL.Type = SetType{Components: yyDollar[3].ComponentTypeList}
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:686
		{
			yyVAL.Type = SequenceType{}
		}
	case 135:
		yyDollar = yyS[yypt-5 : yypt+1]
// asn1.y:687
		{
			yyVAL.Type = SequenceType{}
		}
	case 136:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:688
		{
			yyVAL.Type = SequenceType{Components: yyDollar[3].ComponentTypeList}
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:731
		{
			yyVAL.ComponentTypeList = append(make(ComponentTypeList, 0), yyDollar[1].ComponentType)
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:732
		{
			yyVAL.ComponentTypeList = append(yyDollar[1].ComponentTypeList, yyDollar[3].ComponentType)
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:735
		{
			yyVAL.ComponentType = NamedComponentType{NamedType: yyDollar[1].NamedType}
		}
	case 156:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:736
		{
			yyVAL.ComponentType = NamedComponentType{NamedType: yyDollar[1].NamedType, IsOptional: true}
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:737
		{
			yyVAL.ComponentType = NamedComponentType{NamedType: yyDollar[1].NamedType, Default: yyDollar[3].Value}
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:738
		{
			yyVAL.ComponentType = ComponentsOfComponentType{Type: yyDollar[3].Type}
		}
	case 159:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:744
		{
			yyVAL.Type = yyDollar[3].ChoiceType
		}
	case 160:
		yyDollar = yyS[yypt-5 : yypt+1]
// asn1.y:747
		{
			yyVAL.ChoiceType = ChoiceType{yyDollar[1].AlternativeTypeList, yyDollar[4].ExtensionAdditionAlternativesList}
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:748
		{
			yyVAL.ChoiceType = ChoiceType{AlternativeTypeList: yyDollar[1].AlternativeTypeList}
		}
	case 163:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:755
		{
			yyVAL.ExtensionAdditionAlternativesList = yyDollar[2].ExtensionAdditionAlternativesList
		}
	case 164:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:756
		{
			yyVAL.ExtensionAdditionAlternativesList = make([]ChoiceExtension, 0)
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:759
		{
			yyVAL.ExtensionAdditionAlternativesList = append(make([]ChoiceExtension, 0), yyDollar[1].ExtensionAdditionAlternative)
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:760
		{
			yyVAL.ExtensionAdditionAlternativesList = append(yyDollar[1].ExtensionAdditionAlternativesList, yyDollar[3].ExtensionAdditionAlternative)
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:764
		{
			yyVAL.ExtensionAdditionAlternative = yyDollar[1].NamedType
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:771
		{
			yyVAL.AlternativeTypeList = append(make([]NamedType, 0), yyDollar[1].NamedType)
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:772
		{
			yyVAL.AlternativeTypeList = append(yyDollar[1].AlternativeTypeList, yyDollar[3].NamedType)
		}
	case 171:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:777
		{
			yyVAL.Type = TaggedType{Tag: yyDollar[1].Tag, Type: yyDollar[2].Type}
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:778
		{
			yyVAL.Type = TaggedType{Tag: yyDollar[1].Tag, Type: yyDollar[3].Type, TagType: TAGS_IMPLICIT, HasTagType: true}
		}
	case 173:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:779
		{
			yyVAL.Type = TaggedType{Tag: yyDollar[1].Tag, Type: yyDollar[3].Type, TagType: TAGS_EXPLICIT, HasTagType: true}
		}
	case 174:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:782
		{
			yyVAL.Tag = Tag{Class: yyDollar[2].Class, ClassNumber: yyDollar[3].Value}
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:785
		{
			yyVAL.Value = yyDollar[1].Number
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:786
		{
			yyVAL.Value = yyDollar[1].DefinedValue
		}
	case 177:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:789
		{
			yyVAL.Class = CLASS_UNIVERSAL
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:790
		{
			yyVAL.Class = CLASS_APPLICATION
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:791
		{
			yyVAL.Class = CLASS_PRIVATE
		}
	case 180:
		yyDollar = yyS[yypt-0 : yypt+1]
// asn1.y:792
		{
			yyVAL.Class = CLASS_CONTEXT_SPECIFIC
		}
	case 181:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:797
		{
			yyVAL.Type = SequenceOfType{yyDollar[3].Type}
		}
	case 182:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:798
		{
			yyVAL.Type = SequenceOfType{yyDollar[3].NamedType}
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:801
		{
			yyVAL.Type = SetOfType{yyDollar[3].Type}
		}
	case 184:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:802
		{
			yyVAL.Type = SetOfType{yyDollar[3].NamedType}
		}
	case 185:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:807
		{
			yyVAL.Type = ObjectIdentifierType{}
		}
	case 186:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:812
		{
			yyVAL.ObjectIdentifierValue = yyDollar[2].ObjectIdentifierValue
		}
	case 187:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:813
		{
			yyVAL.ObjectIdentifierValue = NewObjectIdentifierValue(yyDollar[2].DefinedValue).Append(yyDollar[3].ObjectIdentifierValue...)
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:816
		{
			yyVAL.ObjectIdentifierValue = NewObjectIdentifierValue(yyDollar[1].ObjIdComponents)
		}
	case 189:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:817
		{
			yyVAL.ObjectIdentifierValue = NewObjectIdentifierValue(yyDollar[1].ObjIdComponents).Append(yyDollar[2].ObjectIdentifierValue...)
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:820
		{
			yyVAL.ObjIdComponents = ObjectIdElement{Name: yyDollar[1].name}
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:823
		{
			yyVAL.ObjIdComponents = yyDollar[1].DefinedValue
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:826
		{
			yyVAL.ObjIdComponents = ObjectIdElement{Id: yyDollar[1].Number.IntValue()}
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:827
		{
			yyVAL.ObjIdComponents = yyDollar[1].DefinedValue
		}
	case 196:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:831
		{
			switch v := yyDollar[3].ObjIdComponents.(type) {
			case DefinedValue:
				yyVAL.ObjIdComponents = ObjectIdElement{Name: yyDollar[1].name, Reference: &v}
			case ObjectIdElement:
				yyVAL.ObjIdComponents = ObjectIdElement{Name: yyDollar[1].name, Id: v.Id}
			default:
				panic(fmt.Sprintf("Expected DefinedValue or ObjectIdElement from NumberForm, got %v", yyDollar[3].ObjIdComponents))
			}
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:852
		{
			yyVAL.Type = RestrictedStringType{LexType: BMPString}
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:853
		{
			yyVAL.Type = RestrictedStringType{LexType: GeneralString}
		}
	case 202:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:854
		{
			yyVAL.Type = RestrictedStringType{LexType: GraphicString}
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:855
		{
			yyVAL.Type = RestrictedStringType{LexType: IA5String}
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:856
		{
			yyVAL.Type = RestrictedStringType{LexType: ISO646String}
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:857
		{
			yyVAL.Type = RestrictedStringType{LexType: NumericString}
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:858
		{
			yyVAL.Type = RestrictedStringType{LexType: PrintableString}
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:859
		{
			yyVAL.Type = RestrictedStringType{LexType: TeletexString}
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:860
		{
			yyVAL.Type = RestrictedStringType{LexType: T61String}
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:861
		{
			yyVAL.Type = RestrictedStringType{LexType: UniversalString}
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:862
		{
			yyVAL.Type = RestrictedStringType{LexType: UTF8String}
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:863
		{
			yyVAL.Type = RestrictedStringType{LexType: VideotexString}
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:864
		{
			yyVAL.Type = RestrictedStringType{LexType: VisibleString}
		}
	case 213:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:869
		{
			yyVAL.Type = CharacterStringType{}
		}
	case 214:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:874
		{
			yyVAL.Type = TypeReference("GeneralizedTime")
		}
	case 215:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:879
		{
			yyVAL.Type = ConstraintedType{yyDollar[1].Type, yyDollar[2].Constraint}
		}
	case 217:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:887
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].Type}, yyDollar[2].Constraint}
		}
	case 218:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:888
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].Type}, SingleElementConstraint(yyDollar[2].Elements)}
		}
	case 219:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:891
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].NamedType}, yyDollar[2].Constraint}
		}
	case 220:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:892
		{
			yyVAL.Type = ConstraintedType{SequenceOfType{yyDollar[4].NamedType}, SingleElementConstraint(yyDollar[2].Elements)}
		}
	case 221:
		yyDollar = yyS[yypt-4 : yypt+1]
// asn1.y:897
		{
			yyVAL.Constraint = Constraint{ConstraintSpec: yyDollar[2].ConstraintSpec}
		}
	case 222:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:900
		{
			yyVAL.ConstraintSpec = yyDollar[1].SubtypeConstraint
		}
	case 225:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:910
		{
			yyVAL.SubtypeConstraint = yyDollar[1].SubtypeConstraint
		}
	case 226:
		yyDollar = yyS[yypt-5 : yypt+1]
// asn1.y:911
		{
			yyVAL.SubtypeConstraint = append(yyDollar[1].SubtypeConstraint, yyDollar[5].ElementSetSpec)
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:914
		{
			yyVAL.SubtypeConstraint = SubtypeConstraint{yyDollar[1].ElementSetSpec}
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:920
		{
			yyVAL.ElementSetSpec = yyDollar[1].Unions
		}
	case 230:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:921
		{
			yyVAL.ElementSetSpec = yyDollar[2].Exclusions
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:924
		{
			yyVAL.Unions = Unions{yyDollar[1].Intersections}
		}
	case 232:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:925
		{
			yyVAL.Unions = append(yyDollar[1].Unions, yyDollar[3].Intersections)
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:931
		{
			yyVAL.Intersections = Intersections{yyDollar[1].IntersectionElements}
		}
	case 235:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:932
		{
			yyVAL.Intersections = append(yyDollar[1].Intersections, yyDollar[3].IntersectionElements)
		}
	case 237:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:938
		{
			yyVAL.IntersectionElements = IntersectionElements{Elements: yyDollar[1].Elements}
		}
	case 238:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:939
		{
			yyVAL.IntersectionElements = IntersectionElements{Elements: yyDollar[1].Elements, Exclusions: yyDollar[2].Exclusions}
		}
	case 240:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:945
		{
			yyVAL.Exclusions = Exclusions{yyDollar[2].Elements}
		}
	case 245:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:954
		{
			yyVAL.Elements = yyDollar[1].Elements
		}
	case 246:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:956
		{
			yyVAL.Elements = yyDollar[2].ElementSetSpec
		}
	case 251:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:971
		{
			yyVAL.Elements = SingleValue{yyDollar[1].Value}
		}
	case 252:
		yyDollar = yyS[yypt-3 : yypt+1]
// asn1.y:976
		{
			yyVAL.Elements = ValueRange{yyDollar[1].RangeEndpoint, yyDollar[3].RangeEndpoint}
		}
	case 253:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:979
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[1].Value}
		}
	case 254:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:980
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[1].Value, IsOpen: true}
		}
	case 255:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:983
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[1].Value}
		}
	case 256:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:984
		{
			yyVAL.RangeEndpoint = RangeEndpoint{Value: yyDollar[2].Value, IsOpen: true}
		}
	case 258:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:988
		{
			yyVAL.Value = nil
		}
	case 260:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:992
		{
			yyVAL.Value = nil
		}
	case 261:
		yyDollar = yyS[yypt-2 : yypt+1]
// asn1.y:997
		{
			yyVAL.Elements = SizeConstraint{yyDollar[2].Constraint}
		}
	case 262:
		yyDollar = yyS[yypt-1 : yypt+1]
// asn1.y:1002
		{
			yyVAL.Elements = TypeConstraint{yyDollar[1].Type}
		}
	}
	goto yystack /* stack new state and value */
}
